module.exports = {
    MODERATION: 'MODERATION',
    PUBLISHED: 'PUBLISHED',

    ACCESS_CLIENT: 'ACCESS_CLIENT',
    ACCESS_DASHBOARD: 'ACCESS_DASHBOARD',
    ADD_USER: 'ADD_USER',
    ADD_ARTICLE: 'ADD_ARTICLE',
    ADD_OFFER: 'ADD_OFFER',
    ADD_HUB: 'ADD_HUB',
    EDIT_USER: 'EDIT_USER',
    EDIT_ARTICLE: 'EDIT_ARTICLE',
    EDIT_OFFER: 'EDIT_OFFER',
    EDIT_HUB: 'EDIT_HUB',
    DELETE_USER: 'DELETE_USER',
    DELETE_ARTICLE: 'DELETE_ARTICLE',
    DELETE_OFFER: 'DELETE_OFFER',
    DELETE_HUB: 'DELETE_HUB',

    VERIFIED_EMAIL: 'VERIFIED_EMAIL',
    VERIFIED_PHONE: 'VERIFIED_PHONE',
    NOTIFIED_EMAIL: 'NOTIFIED_EMAIL',

    OPEN_CHAT: 'OPEN_CHAT',
    CLOSE_CHAT: 'CLOSE_CHAT',
    SYSTEM_MESSAGING: 'SYSTEM_MESSAGING',
    USER_MESSAGING: 'USER_MESSAGING',
    READED: 'READED',
    UNREADED: 'UNREADED',

    ICON: 'ICON',
    POSTER: 'POSTER',
    HUB: 'HUB',
    OFFER: 'OFFER',
    CHAT: 'CHAT',
    TOUR: 'TOUR',
    PROFILE: 'PROFILE'
}